Balance notifications
blastupio/api-launchpad pull request #43
Opened 2024-05-06 09:56 UTC by 0xniksh

2024-05-06 10:02 UTC, qringie requested changes

2024-05-06 10:02 UTC, qringie commented on app/tasks.py
> +            balance_wei, balance_in_cache, blast_price = await asyncio.gather(
Why would there be a balance from the cache? It seems that it is necessary to always get an up-to-date balance without delays

2024-05-07 07:56 UTC, 0xniksh commented on app/tasks.py
> +            balance_wei, balance_in_cache, blast_price = await asyncio.gather(
It's just used to compare balance with previous execution. so there won't be spam messages if balance less than threshold.
@qringie

2024-05-07 10:35 UTC, astroangrycat commented on app/tg.py
> +        await self.send(msg)
> 🤑  Munzen Order
ID: ...
Amount: $100 (0.01 ETH)
User's wallet: ...

> Onramp wallet balance: 0.01 ETH (put here balance after sending crypto)

2024-05-07 10:37 UTC, astroangrycat commented on app/tg.py
> +        await self.send(msg)
> ⚠️ Onramp Bridge **Warning**
Onramp Bridge wallet balance is low
Balance: **0.01 ETH**
Wallet Address: `0x....` (<a href='{blast_scan_url}'>Blastscan</a>)

2024-05-07 14:04 UTC, astroangrycat commented on app/tg.py
> +        await self.send(msg)
> ✅  COMPLETED Munzen Order
ID: `...`
Transaction Munzen->Bridge: <a href="">tx_hash</a>
Transaction Bridge->User: <a href="">tx_hash</a>
Onramp wallet balance: 0.01 ETH (put here balance after sending crypto)

2024-05-08 11:50 UTC, tripelkarmeliet approved these changes

2024-05-09 13:53 UTC, merged